language: python
python:
   - "3.4"
   - "3.5"
   - "3.6"
   - "3.7"

add-ons:
   apt:
      packages:
         - python3-all
         - python3-setuptools

script: python3 setup.py install --optimize=1
